# Numpy

https://numpy.org/doc/stable/user/index.html

In [3]:
# import library

import numpy as np

## array 1 dimensi

In [3]:
# membuat list

angka = [1,2,3]
angka

[1, 2, 3]

In [4]:
# membuat array dari list

angka_np = np.array(angka)
angka_np

array([1, 2, 3])

In [5]:
# perkalian list

angka*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
# perkalian np.array
# array 1 dimensi/ vektor 1 arah

angka_np*3

array([3, 6, 9])

## array 2 dimensi

In [7]:
# membuat list di dalam list

versi_list = [[1,2,3],[4,5,6],[7,8,9]]
versi_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
# membuat array 2 dimensi

versi_np = np.array(versi_list)
versi_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### arange

In [9]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
np.arange(3,25,4)

array([ 3,  7, 11, 15, 19, 23])

### zeros

In [13]:
# mencetak array dengan nilai 0

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
# mencetak array 2 dimensi dengan tuple

np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones

In [15]:
# mencetak array dengan nilai 1

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((3,1)) # baris, kolom

array([[1.],
       [1.],
       [1.]])

### linspace

In [24]:
# start, stop, berapa banyak
# angka depan dan belakang akan dicetak

np.linspace(0,3,9)

array([0.   , 0.375, 0.75 , 1.125, 1.5  , 1.875, 2.25 , 2.625, 3.   ])

In [22]:
np.linspace(0,8,11)

array([0. , 0.8, 1.6, 2.4, 3.2, 4. , 4.8, 5.6, 6.4, 7.2, 8. ])

### indentity matrix

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Distribusi uniform (0-1)

In [26]:
# bilangan distribusi uniform
# yaitu bilangan range antara 0-1

np.random.rand(7)

array([0.16141998, 0.31595421, 0.59192349, 0.26828949, 0.31426937,
       0.03980344, 0.95898856])

In [30]:
# matriks 2 dimensi

np.random.rand(4,3) # baris, kolom

array([[0.02783174, 0.79711945, 0.01204331],
       [0.25772447, 0.24709515, 0.90663038],
       [0.66450665, 0.01959746, 0.35706454],
       [0.11573037, 0.08001636, 0.65881059]])

## Distribui normal (gaussian) (-0 sd ~)

In [31]:
# bilangan distribusi normal (gaussian) (-0 sd ~)

np.random.randn(12)

array([-0.56515187,  0.09206985,  0.34841017,  0.12886516,  0.31052875,
       -0.86927418, -0.17041398, -0.28355625,  0.86922712,  0.10252333,
        0.4064631 , -0.10416514])

In [32]:
np.random.randn(4,2)

array([[-0.15416638,  1.15796355],
       [-0.61395086,  0.15471649],
       [ 0.05122248,  0.28482213],
       [-0.2847621 ,  0.32353054]])

In [7]:
# bisa dipersingkat

from numpy.random import rand, randn, randint

In [36]:
randn(2,3)

array([[-0.33689391,  0.46829851, -3.44394177],
       [-1.54669872,  0.19543174, -1.01836297]])

In [40]:
randint(2,55)

35

In [42]:
randint(2,5,3)

array([4, 4, 3])

In [44]:
bilangan = randint(2,100,10)
bilangan

array([75, 31, 58,  5, 83, 38, 78, 10, 98, 27])

### reshape

In [45]:
# untuk reshape nilai harus di isi sesuai dengan jumlah bilangan
# jika tidak akan error

bilangan.reshape(2,5)

array([[75, 31, 58,  5, 83],
       [38, 78, 10, 98, 27]])

In [48]:
bilangan2 = randint(2,10,8).reshape(4,2)
bilangan2

array([[3, 6],
       [7, 6],
       [6, 4],
       [9, 9]])

In [55]:
# jika ingin di reshape lagi harus di masukkan variable

bilangan2_re = bilangan2.reshape(2,4)
bilangan2_re

array([[3, 6, 7, 6],
       [6, 4, 9, 9]])

### max, min, argmax, argmin, shape

In [49]:
bilangan.max()

98

In [50]:
bilangan2.min()

3

In [51]:
# melihat value max di index ke berapa
# jika value sama akan diambil paling awal

bilangan.argmax()

8

In [52]:
bilangan2.argmin()

0

In [58]:
bilangan.shape # baris, kolom

(10,)

In [60]:
bilangan2.shape # baris, kolom

(4, 2)

### indexing

In [10]:
nilai_acak = randint(2,12,10)
nilai_acak

array([ 5, 10,  5, 10, 10,  6, 10,  4,  7,  5])

In [12]:
nilai_acak[2] # slicing index ke-2

5

In [14]:
nilai_acak[2:7] #slicing nilai index ke 2 sd 7-1

array([ 5, 10, 10,  6, 10])

In [19]:
nilai_acak2 = np.array([[1,2,2],[4,3,6],[5,7,8]])
nilai_acak2

array([[1, 2, 2],
       [4, 3, 6],
       [5, 7, 8]])

In [20]:
nilai_acak2[2][1] # baris, kolom

7

In [22]:
nilai_acak2[0][2] # baris, kolom

2

In [28]:
nilai_acak2[2,1] # direkomendasikan

7

In [25]:
nilai_acak2[2,2]

8

In [26]:
nilai_acak2[1:2,0:1] # baris, kolom

array([[4]])

In [27]:
nilai_acak2[1:2,0:]

array([[4, 3, 6]])

### indexing dengan boolean

In [36]:
nilai_acak3 = randint(2,13,10)
nilai_acak3

array([12,  9,  7,  6,  6,  5, 11,  3, 11, 11])

In [37]:
nilai_boo = nilai_acak3 > 5
nilai_boo

array([ True,  True,  True,  True,  True, False,  True, False,  True,
        True])

In [38]:
nilai_acak3[nilai_acak3 > 5]

array([12,  9,  7,  6,  6, 11, 11, 11])

### copy

In [15]:
nilai_copy = nilai_acak.copy()

In [16]:
# fungsi copy agar nilai pada nilai_acak tidak berubah

## Operasi di Numpy

In [41]:
operasi = randint(2,20,10)
operasi

array([18, 13, 11, 15, 19, 11, 17, 16,  4, 15])

In [42]:
operasi / 2

array([9. , 6.5, 5.5, 7.5, 9.5, 5.5, 8.5, 8. , 2. , 7.5])

In [44]:
operasi + 8

array([26, 21, 19, 23, 27, 19, 25, 24, 12, 23])

In [45]:
operasi / 0

<ipython-input-45-cd7b15620b1e>:1: RuntimeWarning: divide by zero encountered in true_divide
  operasi / 0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [47]:
0 / operasi

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
1 / operasi

array([0.05555556, 0.07692308, 0.09090909, 0.06666667, 0.05263158,
       0.09090909, 0.05882353, 0.0625    , 0.25      , 0.06666667])

In [50]:
operasi

array([18, 13, 11, 15, 19, 11, 17, 16,  4, 15])

In [49]:
np.sqrt(operasi) # akar

array([4.24264069, 3.60555128, 3.31662479, 3.87298335, 4.35889894,
       3.31662479, 4.12310563, 4.        , 2.        , 3.87298335])

In [51]:
# nilai exp
# e = 2.7182

np.exp(operasi)

array([6.56599691e+07, 4.42413392e+05, 5.98741417e+04, 3.26901737e+06,
       1.78482301e+08, 5.98741417e+04, 2.41549528e+07, 8.88611052e+06,
       5.45981500e+01, 3.26901737e+06])

In [54]:
np.log(operasi)

array([2.89037176, 2.56494936, 2.39789527, 2.7080502 , 2.94443898,
       2.39789527, 2.83321334, 2.77258872, 1.38629436, 2.7080502 ])

In [55]:
np.sin(operasi)

array([-0.75098725,  0.42016704, -0.99999021,  0.65028784,  0.14987721,
       -0.99999021, -0.96139749, -0.28790332, -0.7568025 ,  0.65028784])